plot3<-function(){
elec<- read.table("C:/Data_Science/data/Exploratory data Analysis course project data/household_power_consumption.txt",stringsAsFactors = FALSE, header = TRUE, sep =";")
datestring<-paste(elec$Date,elec$Time)
strp <- strptime(datestring, "%d/%m/%Y %H:%M:%S")
elec<- cbind(elec, strp)
elec$Sub_metering_1 <- as.numeric(elec$Sub_metering_1)
elec$Sub_metering_2 <- as.numeric(elec$Sub_metering_2)
elec$Sub_metering_3 <- as.numeric(elec$Sub_metering_3)
sub<- subset(elec,elec$Date=="1/2/2007" | elec$Date =="2/2/2007")
 with(sub, plot(strp,Sub_metering_1, type="l", xlab="", ylab="Energy sub metering)"))
 lines(sub$strp,sub$Sub_metering_2, col="red",type="l")
 lines(sub$strp,sub$Sub_metering_3, col="blue",type="l")
 legend(c("topright"),lty= 1, lwd=2,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
 dev.copy(png,file="plot3.png", width=480, height=480)
dev.off()
}