plot4<-function(){
elec<- read.table("C:/Data_Science/data/Exploratory data Analysis course project data/household_power_consumption.txt",stringsAsFactors = FALSE, header = TRUE, sep =";")
datestring<-paste(elec$Date,elec$Time)
strp <- strptime(datestring, "%d/%m/%Y %H:%M:%S")
elec<- cbind(elec, strp)
elec$Sub_metering_1 <- as.numeric(elec$Sub_metering_1)
elec$Sub_metering_2 <- as.numeric(elec$Sub_metering_2)
elec$Sub_metering_3 <- as.numeric(elec$Sub_metering_3)
elec$Global_reactive_power<- as.numeric(elec$Global_reactive_power)
elec$Voltage<- as.numeric(elec$Voltage)
elec$Global_active_power<- as.numeric(elec$Global_active_power)
sub<- subset(elec,elec$Date=="1/2/2007" | elec$Date =="2/2/2007")
par(mfrow=c(2,2))
with(sub,{
plot(strp,Global_active_power, type="l", xlab="", ylab="Global_active_power")
plot(strp,Voltage, type="l", xlab="datetime", ylab="Voltage")
 plot(strp,Sub_metering_1, type="l", xlab="", ylab="Energy sub metering)")
  lines(sub$strp,sub$Sub_metering_2, col="red",type="l")
 lines(sub$strp,sub$Sub_metering_3, col="blue",type="l")
 plot(strp,Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
})
dev.copy(png,file="plot4.png", width=480, height=480)
dev.off()
}